# .gitlab-ci.yml

stages:
  - build

default:
  interruptible: true

variables:
  CMAKE_BUILD_TYPE: Release

build-linux:
  stage: build
  image: ubuntu:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq cmake ninja-build build-essential
  script:
    - cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
    - cmake --build build --parallel
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  cache:
    key: cmake-deps-$CI_COMMIT_REF_SLUG
    paths:
      - build/