name: Build on Windows

on:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure
        run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release --parallel
